name: Backend Feature
description: Suggest a new backend feature
title: "feat(backend): "
labels: ["enhancement", "backend"]
assignees:
  - sagarsrc
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      placeholder: What backend feature do you want to add?
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Features
      placeholder: |
        1. Feature one
        2. Feature two
    validations:
      required: true

  - type: textarea
    id: api-changes
    attributes:
      label: API Changes
      placeholder: Describe any API changes if applicable

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      placeholder: |
        - [ ] Deliverable 1
        - [ ] Deliverable 2
