name: Bug Report
description: Report a bug
title: "fix: "
labels: ["bug"]
assignees:
  - sagarsrc
projects:
  - quickcall-dev/1
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - frontend
        - backend
        - infra
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: What's broken?
      placeholder: Describe what's not working
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen instead?

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.2.0"
