name: Chore / Maintenance
description: Infrastructure, DevOps, or cleanup task
title: "chore: "
labels: ["chore"]
assignees:
  - sagarsrc
projects:
  - quickcall-dev/1
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - infra
        - backend
        - frontend
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: What needs to be done?
      placeholder: Describe the task
    validations:
      required: true
