name: Documentation
description: Documentation improvements
title: "docs: "
labels: ["documentation"]
assignees:
  - sagarsrc
projects:
  - quickcall-dev/1
body:
  - type: textarea
    id: what
    attributes:
      label: What needs documentation?
      placeholder: Describe what's missing or unclear
    validations:
      required: true
