name: Feature Request
description: Suggest a new feature
title: "feat: "
labels: ["enhancement"]
assignees:
  - sagarsrc
projects:
  - quickcall-dev/1
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - frontend
        - backend
        - infra
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What do you want?
      placeholder: Describe the feature clearly
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      placeholder: What problem does this solve?
