name: Release
description: Track a new release
title: "chore: Release v"
labels: ["release"]
assignees:
  - sagarsrc
projects:
  - quickcall-dev/1
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.2.1"
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Changes
      placeholder: |
        - Change 1
        - Change 2
    validations:
      required: true
